### ISSUE TITLE
Redesign Frontend

### ISSUE THREAD

**Issue by freddyheppell** [projectcitybuild/web#443]
These are all the public-facing views:

## General

- [x] Homepage (completed in #350)
- [x] Panel (obselete as of  #365)
- [x] Ban List

## Account
- [x] Settings (#444)
  - [x] Post-email change info
  - [x] Email change finished
- [x] Security
  - [x] 2FA Setup Page
  - [x] 2FA disable page
  - [x] Backup code refresh confirmation page
  - [x] Backup code refresh new code page
- [x] Donations
- [x] Game Accounts

## Donation
- [x] Donation home (#463)
- [x] Donation error (#463)
- [x] Donation thanks (#463)

## Authentication
- [x] Login (completed in #375)
- [x] Enter 2FA code page (#490)
- [x] Enter 2FA backup code page (#490)
- [x] Reenter password page (#490)

## Minecraft Auth
- [x] Error page

## Password Reset
- [x] Request reset
- [x] Reset form
- [x] Reset success

## Register
-  [x] Register (#490)
-  [x] Register success (#490)
-  [x] Email confirmed (#490)

**Comment by andyksaw** [comment]
Finished here #549
